version: '3'

services:

  neo4j:
    build: ./neo4j
    ports:
      - 32847:32847
      - 32846:32846
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true

  api:
    build: ./api
    ports:
      - 4001:4001
    environment:
      - NEO4J_URI=bolt://35.174.207.184:32846
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=ladder-policies-plead
      - GRAPHQL_LISTEN_PORT=4001
      - GRAPHQL_URI=http://api:4001/graphql      
      
    links:
    - neo4j
    depends_on:
    - neo4j

  ui:
    build: ./ui-react
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GRAPHQL_URI=/graphql
      - PROXY=http://api:4001/graphql
    links:
    - api
    depends_on:
    - api
